### ISSUE TITLE
Restrictions JSON design

### ISSUE THREAD

**Issue by S-Maciejewski** [TheCommonCold/covid-info-service#10]
Design a format of restrictions data in JSON. Keep maintainability in mind, it will be often updated and perhaps extended

**Comment by Vulwsztyn** [comment]
```
interface Restriction {
text: string
}

interface Restrictions {
restrictions: []Restriction
}
```
?

**Comment by lukher-dev** [comment]
![image](https://user-images.githubusercontent.com/26366303/97787926-60ae5380-1bb5-11eb-8531-fa4b613949bf.png)


Moja propozycja jsona z restrykacjami. Lista różnych kategorii, w których zawarte są restrykcje i ich tytuły.

**Comment by S-Maciejewski** [comment]
Imo wersja z kategoriami będzie łatwiejsza do ogarnięcia na froncie i też pewnie trochę bardziej maintainable jak będzie się coś zmieniało

**Comment by lukher-dev** [comment]
Koniec końców zmieniłem lekko nazwy, ale layout ten sam. Obecnie to jest zaimplementowane na branchu frontend.
