### ISSUE TITLE
Implement site layout

### ISSUE THREAD

**Issue by S-Maciejewski** [TheCommonCold/covid-info-service#4]
Design basic layout to display the restrictions and stats

DoD: Site displays a section for restrictions and a section for statistics

**Comment by lukher-dev** [comment]
![image](https://user-images.githubusercontent.com/26366303/97790294-b68bf700-1bc7-11eb-8682-04783da1db32.png)

Moja propozycja frontu. Jakiś landig page z minimalnymi info (np zarażenia dzisiaj, aktywne casy, data najnowszych obostrzeń) i dwoma guzikami. Jeden przenosi nas w świat obostrzeń, a drugi w świat statystyk. To na screenie to byłby świat obostrzeń. Ofc wszystko do dopracowania tak, żeby było dokładnie tak jak chcemy.

**Comment by S-Maciejewski** [comment]
Brzmi jak dobry plan
