### ISSUE TITLE
Implement JSON data service in React

### ISSUE THREAD

**Issue by S-Maciejewski** [TheCommonCold/covid-info-service#5]
React frontend app should have a service for loading JSON data saved in the app directory

**Comment by lukher-dev** [comment]
Czy nie łatwiej po prostu importować tego jsona? Ja zwykłem używać do takich rzeczy takiej konstrukcji 
![image](https://user-images.githubusercontent.com/26366303/97779263-2e80ff80-1b7d-11eb-8482-3947b4f9d720.png)

**Comment by S-Maciejewski** [comment]
Bardziej chodziło mi o to, żeby tę strukturę JSONa jakoś obsłużyć po stronie klienta, ale może nie trzeba, tylko wszystko ciągnąć z tak powstałego obiektu
